/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing AccountUsageStatisticsInterval
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountUsageStatisticsIntervalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountUsageStatisticsInterval
        //private AccountUsageStatisticsInterval instance;

        public AccountUsageStatisticsIntervalTests()
        {
            // TODO uncomment below to create an instance of AccountUsageStatisticsInterval
            //instance = new AccountUsageStatisticsInterval();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountUsageStatisticsInterval
        /// </summary>
        [Fact]
        public void AccountUsageStatisticsIntervalInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountUsageStatisticsInterval
            //Assert.IsType<AccountUsageStatisticsInterval>(instance);
        }
    }
}
