/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing ApiUsageEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiUsageEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiUsageEntry
        //private ApiUsageEntry instance;

        public ApiUsageEntryTests()
        {
            // TODO uncomment below to create an instance of ApiUsageEntry
            //instance = new ApiUsageEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiUsageEntry
        /// </summary>
        [Fact]
        public void ApiUsageEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiUsageEntry
            //Assert.IsType<ApiUsageEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Fact]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
