/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing ApiUsageDataTransfer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiUsageDataTransferTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiUsageDataTransfer
        //private ApiUsageDataTransfer instance;

        public ApiUsageDataTransferTests()
        {
            // TODO uncomment below to create an instance of ApiUsageDataTransfer
            //instance = new ApiUsageDataTransfer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiUsageDataTransfer
        /// </summary>
        [Fact]
        public void ApiUsageDataTransferInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiUsageDataTransfer
            //Assert.IsType<ApiUsageDataTransfer>(instance);
        }

        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Fact]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
    }
}
