/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CommodityTypesList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommodityTypesListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommodityTypesList
        //private CommodityTypesList instance;

        public CommodityTypesListTests()
        {
            // TODO uncomment below to create an instance of CommodityTypesList
            //instance = new CommodityTypesList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommodityTypesList
        /// </summary>
        [Fact]
        public void CommodityTypesListInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommodityTypesList
            //Assert.IsType<CommodityTypesList>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
