/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CommodityType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommodityTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommodityType
        //private CommodityType instance;

        public CommodityTypeTests()
        {
            // TODO uncomment below to create an instance of CommodityType
            //instance = new CommodityType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommodityType
        /// </summary>
        [Fact]
        public void CommodityTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommodityType
            //Assert.IsType<CommodityType>(instance);
        }
    }
}
