/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CommodityTypeObj
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommodityTypeObjTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommodityTypeObj
        //private CommodityTypeObj instance;

        public CommodityTypeObjTests()
        {
            // TODO uncomment below to create an instance of CommodityTypeObj
            //instance = new CommodityTypeObj();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommodityTypeObj
        /// </summary>
        [Fact]
        public void CommodityTypeObjInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommodityTypeObj
            //Assert.IsType<CommodityTypeObj>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
    }
}
