/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing ConversionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversionInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversionInfo
        //private ConversionInfo instance;

        public ConversionInfoTests()
        {
            // TODO uncomment below to create an instance of ConversionInfo
            //instance = new ConversionInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversionInfo
        /// </summary>
        [Fact]
        public void ConversionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversionInfo
            //Assert.IsType<ConversionInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
    }
}
