/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CountryObj
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CountryObjTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CountryObj
        //private CountryObj instance;

        public CountryObjTests()
        {
            // TODO uncomment below to create an instance of CountryObj
            //instance = new CountryObj();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountryObj
        /// </summary>
        [Fact]
        public void CountryObjInstanceTest()
        {
            // TODO uncomment below to test "IsType" CountryObj
            //Assert.IsType<CountryObj>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
    }
}
