/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CryptoConversion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CryptoConversionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CryptoConversion
        //private CryptoConversion instance;

        public CryptoConversionTests()
        {
            // TODO uncomment below to create an instance of CryptoConversion
            //instance = new CryptoConversion();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CryptoConversion
        /// </summary>
        [Fact]
        public void CryptoConversionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CryptoConversion
            //Assert.IsType<CryptoConversion>(instance);
        }

        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
