/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CryptoExchangesList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CryptoExchangesListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CryptoExchangesList
        //private CryptoExchangesList instance;

        public CryptoExchangesListTests()
        {
            // TODO uncomment below to create an instance of CryptoExchangesList
            //instance = new CryptoExchangesList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CryptoExchangesList
        /// </summary>
        [Fact]
        public void CryptoExchangesListInstanceTest()
        {
            // TODO uncomment below to test "IsType" CryptoExchangesList
            //Assert.IsType<CryptoExchangesList>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
