/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CryptoConversionQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CryptoConversionQueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CryptoConversionQuery
        //private CryptoConversionQuery instance;

        public CryptoConversionQueryTests()
        {
            // TODO uncomment below to create an instance of CryptoConversionQuery
            //instance = new CryptoConversionQuery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CryptoConversionQuery
        /// </summary>
        [Fact]
        public void CryptoConversionQueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" CryptoConversionQuery
            //Assert.IsType<CryptoConversionQuery>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Precision'
        /// </summary>
        [Fact]
        public void PrecisionTest()
        {
            // TODO unit test for the property 'Precision'
        }
    }
}
