/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing CursorPageTCustomizedSymbolsOutFull
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CursorPageTCustomizedSymbolsOutFullTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CursorPageTCustomizedSymbolsOutFull
        //private CursorPageTCustomizedSymbolsOutFull instance;

        public CursorPageTCustomizedSymbolsOutFullTests()
        {
            // TODO uncomment below to create an instance of CursorPageTCustomizedSymbolsOutFull
            //instance = new CursorPageTCustomizedSymbolsOutFull();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CursorPageTCustomizedSymbolsOutFull
        /// </summary>
        [Fact]
        public void CursorPageTCustomizedSymbolsOutFullInstanceTest()
        {
            // TODO uncomment below to test "IsType" CursorPageTCustomizedSymbolsOutFull
            //Assert.IsType<CursorPageTCustomizedSymbolsOutFull>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Fact]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }

        /// <summary>
        /// Test the property 'CurrentPageBackwards'
        /// </summary>
        [Fact]
        public void CurrentPageBackwardsTest()
        {
            // TODO unit test for the property 'CurrentPageBackwards'
        }

        /// <summary>
        /// Test the property 'PreviousPage'
        /// </summary>
        [Fact]
        public void PreviousPageTest()
        {
            // TODO unit test for the property 'PreviousPage'
        }

        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
    }
}
