/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorResponseBody
        //private ErrorResponseBody instance;

        public ErrorResponseBodyTests()
        {
            // TODO uncomment below to create an instance of ErrorResponseBody
            //instance = new ErrorResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorResponseBody
        /// </summary>
        [Fact]
        public void ErrorResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorResponseBody
            //Assert.IsType<ErrorResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
