/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorDetails
        //private ErrorDetails instance;

        public ErrorDetailsTests()
        {
            // TODO uncomment below to create an instance of ErrorDetails
            //instance = new ErrorDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorDetails
        /// </summary>
        [Fact]
        public void ErrorDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorDetails
            //Assert.IsType<ErrorDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
