/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing LastQuote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LastQuoteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LastQuote
        //private LastQuote instance;

        public LastQuoteTests()
        {
            // TODO uncomment below to create an instance of LastQuote
            //instance = new LastQuote();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LastQuote
        /// </summary>
        [Fact]
        public void LastQuoteInstanceTest()
        {
            // TODO uncomment below to test "IsType" LastQuote
            //Assert.IsType<LastQuote>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

        /// <summary>
        /// Test the property 'Ask'
        /// </summary>
        [Fact]
        public void AskTest()
        {
            // TODO unit test for the property 'Ask'
        }

        /// <summary>
        /// Test the property 'Bid'
        /// </summary>
        [Fact]
        public void BidTest()
        {
            // TODO unit test for the property 'Bid'
        }

        /// <summary>
        /// Test the property 'Mid'
        /// </summary>
        [Fact]
        public void MidTest()
        {
            // TODO unit test for the property 'Mid'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
    }
}
