/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradewatch.Model;
using Tradewatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradewatch.Test.Model
{
    /// <summary>
    ///  Class for testing ValidationErrorLocInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidationErrorLocInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidationErrorLocInner
        //private ValidationErrorLocInner instance;

        public ValidationErrorLocInnerTests()
        {
            // TODO uncomment below to create an instance of ValidationErrorLocInner
            //instance = new ValidationErrorLocInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidationErrorLocInner
        /// </summary>
        [Fact]
        public void ValidationErrorLocInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidationErrorLocInner
            //Assert.IsType<ValidationErrorLocInner>(instance);
        }
    }
}
