/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tradewatch.Client.OpenAPIDateConverter;

namespace Tradewatch.Model
{
    /// <summary>
    /// Data interval
    /// </summary>
    /// <value>Data interval</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountUsageStatisticsInterval
    {
        /// <summary>
        /// Enum _1h for value: 1h
        /// </summary>
        [EnumMember(Value = "1h")]
        _1h = 1,

        /// <summary>
        /// Enum _1d for value: 1d
        /// </summary>
        [EnumMember(Value = "1d")]
        _1d = 2
    }

}
