/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tradewatch.Client.OpenAPIDateConverter;

namespace Tradewatch.Model
{
    /// <summary>
    /// Usage history entry
    /// </summary>
    [DataContract(Name = "ApiUsageEntry")]
    public partial class ApiUsageEntry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiUsageEntry" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiUsageEntry() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiUsageEntry" /> class.
        /// </summary>
        /// <param name="requests">requests (required).</param>
        /// <param name="data">data (required).</param>
        public ApiUsageEntry(int requests = default(int), ApiUsageDataTransfer data = default(ApiUsageDataTransfer))
        {
            this.Requests = requests;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for ApiUsageEntry and cannot be null");
            }
            this.Data = data;
        }

        /// <summary>
        /// Gets or Sets Requests
        /// </summary>
        [DataMember(Name = "requests", IsRequired = true, EmitDefaultValue = true)]
        public int Requests { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public ApiUsageDataTransfer Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiUsageEntry {\n");
            sb.Append("  Requests: ").Append(Requests).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
