/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tradewatch.Client.OpenAPIDateConverter;

namespace Tradewatch.Model
{
    /// <summary>
    /// Defines CommodityType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommodityType
    {
        /// <summary>
        /// Enum Agricultural for value: agricultural
        /// </summary>
        [EnumMember(Value = "agricultural")]
        Agricultural = 1,

        /// <summary>
        /// Enum Energy for value: energy
        /// </summary>
        [EnumMember(Value = "energy")]
        Energy = 2,

        /// <summary>
        /// Enum Metal for value: metal
        /// </summary>
        [EnumMember(Value = "metal")]
        Metal = 3,

        /// <summary>
        /// Enum All for value: all
        /// </summary>
        [EnumMember(Value = "all")]
        All = 4
    }

}
