/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tradewatch.Client.OpenAPIDateConverter;

namespace Tradewatch.Model
{
    /// <summary>
    /// The country associated with the symbol (see ISO 3166-1 alpha-2)
    /// </summary>
    /// <value>The country associated with the symbol (see ISO 3166-1 alpha-2)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Country
    {
        /// <summary>
        /// Enum Fr for value: fr
        /// </summary>
        [EnumMember(Value = "fr")]
        Fr = 1,

        /// <summary>
        /// Enum Us for value: us
        /// </summary>
        [EnumMember(Value = "us")]
        Us = 2,

        /// <summary>
        /// Enum De for value: de
        /// </summary>
        [EnumMember(Value = "de")]
        De = 3,

        /// <summary>
        /// Enum Nz for value: nz
        /// </summary>
        [EnumMember(Value = "nz")]
        Nz = 4,

        /// <summary>
        /// Enum Nl for value: nl
        /// </summary>
        [EnumMember(Value = "nl")]
        Nl = 5,

        /// <summary>
        /// Enum Uk for value: uk
        /// </summary>
        [EnumMember(Value = "uk")]
        Uk = 6,

        /// <summary>
        /// Enum Es for value: es
        /// </summary>
        [EnumMember(Value = "es")]
        Es = 7,

        /// <summary>
        /// Enum Cn for value: cn
        /// </summary>
        [EnumMember(Value = "cn")]
        Cn = 8,

        /// <summary>
        /// Enum Ch for value: ch
        /// </summary>
        [EnumMember(Value = "ch")]
        Ch = 9,

        /// <summary>
        /// Enum Gr for value: gr
        /// </summary>
        [EnumMember(Value = "gr")]
        Gr = 10,

        /// <summary>
        /// Enum Be for value: be
        /// </summary>
        [EnumMember(Value = "be")]
        Be = 11,

        /// <summary>
        /// Enum Pt for value: pt
        /// </summary>
        [EnumMember(Value = "pt")]
        Pt = 12,

        /// <summary>
        /// Enum It for value: it
        /// </summary>
        [EnumMember(Value = "it")]
        It = 13,

        /// <summary>
        /// Enum All for value: all
        /// </summary>
        [EnumMember(Value = "all")]
        All = 14
    }

}
