/*
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tradewatch.Client.OpenAPIDateConverter;

namespace Tradewatch.Model
{
    /// <summary>
    /// Defines SymbolsListMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SymbolsListMode
    {
        /// <summary>
        /// Enum Full for value: full
        /// </summary>
        [EnumMember(Value = "full")]
        Full = 1,

        /// <summary>
        /// Enum Base for value: base
        /// </summary>
        [EnumMember(Value = "base")]
        Base = 2
    }

}
